Feature/pap 9 implement real time direct messaging dm functionality
project-ascend-io/intracom-be-06-2024 pull request #5
Opened 2024-06-30 02:16 UTC by bobbygrdn

I have implemented basic socket connection and functionality. I also created a file to mock a client connection so we do not need to utilize the frontend for testing purposes. The file sends and receives a message from the server when the socket connects and disconnects. This should show proof of concept for the backend that we can scale further once it is tested by others.

2024-08-26 18:48 UTC, oestrada1001 commented
Great job @bobbygrdn! Code looks good. Let's keep this PR open until we can integrate it locally with the frontend to test it.

2024-11-12 17:49 UTC, oestrada1001 requested changes
Great job! I requested one minor improvement.

2024-11-12 18:04 UTC, bobbygrdn commented on src/socket.ts
> +    mode: 'development',
No. This is just a setup to add the AdminUI capabilities for development. We can add this to the production environment, but right now it serves as a debugging tool.

Here is the reference: https://socket.io/docs/v4/admin-ui/

2024-11-12 18:37 UTC, oestrada1001 requested changes

2024-11-12 18:37 UTC, oestrada1001 commented on src/socket.ts
> +    mode: 'development',
Great. That make sense for auth. Let's make `mode` the same value as NODE_ENV. Leveraging the .env will allow us to toggle the mode type based on environment without committing a new chance.

2024-11-12 18:39 UTC, bobbygrdn commented on src/socket.ts
> +    mode: 'development',
Sounds good. That will be an easy update. 😁

2024-11-15 00:36 UTC, bobbygrdn commented on src/socket.ts
> +    mode: 'development',
I have updated the code we discussed to reference the environment for mode and added authentication credentials, which will be retrieved from the environment file. Let me know what you think.

2024-11-19 17:11 UTC, oestrada1001 approved these changes
Love the abstraction! Great job @bobbygrdn 🙌

2024-11-20 21:02 UTC, merged

2025-02-12 22:44 UTC, oestrada1001 commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/project-ascend-io/intracom-backend/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: